# Generated by Django 3.0.4 on 2020-03-23 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='metadato',
        ),
        migrations.AddField(
            model_name='bills',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='metadata',
            field=models.TextField(blank=True, null=True, verbose_name='METADATA'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='company_id',
            field=models.IntegerField(verbose_name='COMPAÑIA'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='FECHA CREADO'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='receiver',
            field=models.CharField(max_length=255, verbose_name='RECEPTOR'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='type_id',
            field=models.IntegerField(verbose_name='TIPO ID'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='uuid',
            field=models.CharField(max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='xml',
            field=models.TextField(verbose_name='XML'),
        ),
    ]
